### ISSUE TITLE
Where is @@setup-xmpp?

### ISSUE THREAD

**Issue by alecghica** [collective/collective.xmpp.core#1]
In README under https://github.com/collective/collective.xmpp.core is mentioned several times to run @@setup-xmpp upon your Plone portal. This @@setup-xmpp doesn't seem to exist (anymore?). Any clue?

**Comment by jcbrand** [comment]
Hi @alecghica, I removed @@setup-xmpp and replaced it with the configlet in the control panel. I'll update the readme to remove those references.

**Comment by jcbrand** [comment]
Fixed in 7621908ce76e9514292fb113d2d87b9bc41e5678
