### ISSUE TITLE
Users are only being auto-subscribed to other users added in that current session

### ISSUE THREAD

**Issue by jcbrand** [collective/collective.xmpp.core#12]
Spotted by @alecghica in #10

> I see that when you manually register users they are subscribed only between those added in that particular adding session. Like if I add user1 and user2 they will be subscribed to each other, then later on if I register user3 and user4 they will be subscribed only between them and not with all the other registered users (as expected) like user1 and 2. 

This is a bug, and I can see why. **registerXMPPUsers** in _collective.xmpp.core/utils/setup.py_ was written with the **Register ALL users** use-case in mind, so it only subscribes you to the users added in that session.

**Comment by alecghica** [comment]
Fixed under #10
