### ISSUE TITLE
New users should only be auto-subscribed to existing XMPP users (not whole Plone site)

### ISSUE THREAD

**Issue by jcbrand** [collective/collective.xmpp.core#13]
Spotted by @alecghica in #10 

> > Also when a user is registered when a new Plone user there is an attempt to register it towards all the Plone users, no matter what they are registered into the jabber server or not (even so I noticed the suggestion is sent but the user registered this way has no contacts in his list, this is a bug right?).
> 
> Yeah, sounds like a bug.
> 
> In line 67 in _collective.xmpp.core/subscribers/user_management.py_, the JIDs for all users in the Plone site are fetched.
> 
> So we need to get the JIDs of all users who are currently registered on XMPP, and only subscribe the user to those.
> 
> We can use this same approach for the other bug mentioned above.

**Comment by alecghica** [comment]
Fixed under #10
