### ISSUE TITLE
ComponentLookup error when registering all users

### ISSUE THREAD

**Issue by ichim-david** [collective/collective.xmpp.core#20]
ComponentLookupError(<InterfaceClass plone.registry.interfaces.IRegistry>, '') when Adding all users after I have used the membershipdata.csv from collective.loremipsum to create those 500 dummy buttons.

This happened when it got to line 
utils/setup.py line 72
iq['to'] = getXMPPDomain()

At this point the item['node'] is u'all users/@494-522 and by adding this check I got rid of this error however I am thinking that this user might pose errors in other places and it might need to be dealt with in other ways.

My workaround:
if 'all users' in item['node']:
    continue

**Comment by jcbrand** [comment]
It doesn't look as if your code is up to date.  I have something else at line 72.
