### ISSUE TITLE
ComponentLookupError: (<InterfaceClass collective.xmpp.core.interfaces.IZopeReactor>, '')

### ISSUE THREAD

**Issue by ciroiriarte** [collective/collective.xmpp.core#26]
Hi, running a fresh Plone 4.3 install and adding collective.xmpp.core I get this error after enabling the collective.xmpp.core module:

  Module ZPublisher.Publish, line 143, in publish
  Module zope.event, line 31, in notify
  Module zope.component.event, line 24, in dispatch
  Module zope.component._api, line 136, in subscribers
  Module zope.component.registry, line 321, in subscribers
  Module zope.interface.adapter, line 585, in subscribers
  Module collective.xmpp.core.subscribers.startup, line 54, in setUpAdminClient
  Module collective.xmpp.core.subscribers.startup, line 27, in createAdminClient
  Module collective.xmpp.core.client, line 160, in __init__
  Module collective.xmpp.core.client, line 88, in **init**
  Module zope.component._api, line 169, in getUtility
ComponentLookupError: (<InterfaceClass collective.xmpp.core.interfaces.IZopeReactor>, '')

Is this expected?

**Comment by jcbrand** [comment]
Looks like you didn't register the reactor. You need the following in your buildout.cfg:

```
zcml-additional =
  <configure xmlns="http://namespaces.zope.org/zope">
    <include package="collective.xmpp.core" file="reactor.zcml" />
  </configure>
```
